-- Content Management System

DROP DATABASE IF EXISTS CMS_db;

CREATE DATABASE CMS_db;

USE CMS_db;

CREATE TABLE DEPARTMENT(
id INTEGER AUTO_INCREMENT NOT NULL,
NAME VARCHAR (30),
PRIMARY KEY (id)
);

CREATE TABLE ROLE(
id INTEGER AUTO_INCREMENT NOT NULL,
title VARCHAR (30),
salary DECIMAL, 
department_id INT,
FOREIGN KEY (department_id) REFERENCES DEPARTMENT (id),
PRIMARY KEY (id)
);

CREATE TABLE EMPLOYEE(
id INTEGER AUTO_INCREMENT NOT NULL,
first_name VARCHAR(30),
last_name VARCHAR (30),
role_id INT ,
manager_id INT,
FOREIGN KEY (role_id) REFERENCES ROLE (id),
FOREIGN KEY (manager_id) REFERENCES EMPLOYEE (id),
PRIMARY KEY (id)
);
