INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ('Joshua', 'Bernardo', 1, 10); 

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ('Dave', 'Impey', 5, 13); 